name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Avoid errors if requirements.txt doesn't exist

    # Step 4: Run linter
    - name: Run flake8 linter
      run: |
        python -m pip install flake8
        flake8 src/ tests/  # Adjust paths as needed

    # Step 5: Run tests
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"
